cloud:
  consul:
    host: localhost
    port: 8500
    # 服务发现配置
    discovery:
      enabled: true
      register: true
      prefer-ip-address: true
      health-check-interval: 10s
      health-check-critical-timeout: 30s
      health-check-path: /actuator/health

      service-name: ${spring.application.name}
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-adress}:${server.port}